name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [ '16' ]
        runs-on: [ macos-latest, windows-latest ]

    runs-on: ${{ matrix.runs-on }}

    # env:
    #   CSC_IDENTITY_AUTO_DISCOVERY: false
    #   GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - run: npm install
    - run: npm run make
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.runs-on }}
        path: |
          out/**/*.zip
          out/**/*.exe
          out/**/*.nupkg
        if-no-files-found: error
