name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [ '16' ]
        make-cmd: ['make']
        runs-on: ['']
        target-env: [ macos-latest, windows-latest, windows-ia32 ]
        include:
        - target-env: macos-latest
          runs-on: macos-latest
        - target-env: windows-latest
          runs-on: windows-latest
        - target-env: windows-ia32
          runs-on: windows-latest
          make-cmd: 'ia32:make'

    runs-on: ${{ matrix.runs-on }}

    # env:
    #   CSC_IDENTITY_AUTO_DISCOVERY: false
    #   GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - run: npm install
    - run: npm run ${{ matrix.make-cmd }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target-env }}
        path: |
          out/**/*.zip
          out/**/*.exe
          out/**/*.nupkg
        if-no-files-found: error
