name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: macos-latest
          arch: 'default'
          make-cmd: 'make'
        - os: windows-latest
          arch: 'x64'
          make-cmd: 'make'
        - os: windows-latest
          arch: 'ia32'
          make-cmd: 'ia32:make'

    runs-on: ${{ matrix.os }}

    # env:
    #   CSC_IDENTITY_AUTO_DISCOVERY: false
    #   GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        check-latest: true
    - run: npm install
    - run: npm run ${{ matrix.make-cmd }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}
        path: |
          out/**/*.zip
          out/**/*.exe
          out/**/*.nupkg
        if-no-files-found: error
